### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ABCAI93** [yanxp/SSM-Pytorch#2]
hello
when I run the code, it shows missing files.

The error message is as follows.
ModuleNotFoundError: No module named 'nms._ext.nms._nms'
ModuleNotFoundError: No module named 'layer_utils.roi_pooling._ext.roi_pooling._roi_pooling'

Could you supply me with these two documents?

**Comment by yanxp** [comment]
Hello,you need to compile first.

**Comment by kezewang** [comment]
Dear Yonghuicai,

Thanks for your kind attention to our work!

According to your description, you need to compile some codes by following:
cd ./lib/
make
cd ../

Best Regards,
Keze
