### ISSUE TITLE
Variable not defined in help.py

### ISSUE THREAD

**Issue by RiccardoGrigoletto** [yanxp/SSM-Pytorch#7]
Hello there, I am trying different things with the code.

I encountered the following error:

```
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 236, in <module>
    v,v_val = judge_uv(loss,gamma,clslambda)
  File "/home/riccardo/SSM-Pytorch/tools/../lib/utils/help.py", line 135, in judge_uv
    if(lsum > threshold):
NameError: name 'threshold' is not defined
```
Could you please provide some suggestions on this? Thank you.

**Comment by RiccardoGrigoletto** [comment]
Maybe replace it with the variable `gamma`?

**Comment by yanxp** [comment]
@RiccardoGrigoletto Yes, threshold is gamma. I have updated it. Thanks.
