### ISSUE TITLE
Variable not defined in trainval_net.py

### ISSUE THREAD

**Issue by RiccardoGrigoletto** [yanxp/SSM-Pytorch#8]
I found what is probably just a typo in trainval_net.py. the right variable might be `im_boxes`.

```
Traceback (most recent call last):
  File "/home/riccardo/SSM-Pytorch/tools/trainval_net.py", line 267, in <module>
    ss_avg_score.append(ss_accum_score/len(img_boxes))
NameError: name 'img_boxes' is not defined
```

**Comment by yanxp** [comment]
Sorry for that, I have updated it. By the way, you can refer to the original implementation: https://github.com/yanxp/SSM/.

**Comment by RiccardoGrigoletto** [comment]
Thank you :)
